from flask import Blueprint, request, jsonify
from ..db import engine
from ..nlp_parser import generate_sql, summarize_results, generate_insight
import pandas as pd
from sqlalchemy import text

api_bp = Blueprint("api", __name__)

def clean_sql(sql: str) -> str:
    """
    Remove markdown code blocks and extra whitespace from SQL generated by AI.
    """

    sql = sql.strip()
    if sql.startswith("```sql"):
        sql = sql[len("```sql"):].strip()
    if sql.startswith("```"):
        sql = sql[len("```"):].strip()
    if sql.endswith("```"):
        sql = sql[:-len("```")].strip()
    return sql


@api_bp.route("/api/query", methods=["POST"])
def api_query():
    data = request.json
    question = data.get("question")

    sql, explanation = generate_sql(question)
    if not sql:
        return jsonify({"response": explanation})

    sql = clean_sql(sql)

    with engine.connect() as conn:
        result = conn.execute(text(sql))
        df = pd.DataFrame(result.fetchall(), columns=result.keys())

    readable = summarize_results(question, df)

    return jsonify({"response": readable})

